[클린코드 5기 손수림] 계산기 미션
next-step/js-jest-calculator pull request #15
Opened 2023-07-20 18:35 UTC by sonsurim

## Summary
- [X] 2개의 숫자에 대해 덧셈이 가능하다.
- [X] 2개의 숫자에 대해 뺄셈이 가능하다.
- [X] 2개의 숫자에 대해 곱셈이 가능하다.
- [X] 2개의 숫자에 대해 나눗셈이 가능하다.
- [X] 숫자는 한번에 최대 3자리 수까지만 다룰 수 있다.
- [X] 계산 결과를 표현할 때 소수점 이하는 버림한다.

## Issues
계산기가 이렇게 고려해야할 엣지 케이스가 많은지 처음 알게 되었습니다..🥹
- Q. 이렇게 엣지 케이스가 많아서 검증하기 어려운 경우에는 어느 정도까지 테스트 코드를 작성해야할 지 여쭤보고 싶습니다!
- Q. 비슷한 로직들이 많은데 추상화 하는 부분이 어려운 것 같습니다.. 어떤 관점으로 추상화할 수 있을지, 어떤 관점으로 추상화 하면 좋을지 여쭤보고 싶습니다!
- Q. 테스트 코드를 작성할 때, 어느 정도까지 테스트를 해야할지에 대한 고민이 드는 것 같습니다..! 혹시 리뷰어님의 기준이 있으시다면 여쭤보고 싶습니다!

2023-07-21 09:09 UTC, carlos-dev-yang requested changes
안녕하세요 수림님, 이번 계산기 미션을 같이 리뷰하게 된 양명수 입니다.

commit을 작업 단위별로 잘 나눠주셔서 무척 편하게 리뷰 했습니다.
전체적으로 잘 짜주셔서 작은 내용들만 같이 체크해보고 수정해주시면 좋을 것 같습니다!

1. 전체 프로그래밍의 의미를 결정 짓는 상수들은 이름이 조금 길어도 명확한게 좋습니다.
2. 테스트 케이스에서 조금 더 다양한 케이스에 대해 작성해주시면 더 좋을 것 같습니다.
3. 반복되는 함수들을 어떻게 하면 중복호출하지 않을지 고민이 필요합니다.

--- 

질문에 대한 답변을 드려볼게요!

> Q. 이렇게 엣지 케이스가 많아서 검증하기 어려운 경우에는 어느 정도까지 테스트 코드를 작성해야할 지 여쭤보고 싶습니다!

주어진 요구조건에 부합하는 테스트 케이스가 가장 우선 필요합니다. 이 테스트 케이스를 기반으로 기본적인 코드를 올리게 됩니다. (여기까지는 잘 수행하신 것 같습니다.)

[1f88677](https://github.com/next-step/js-jest-calculator/pull/15/commits/1f8867783bfc3fc1c87419ace4e35f0c73ea59dd) 커밋과 [186245e](https://github.com/next-step/js-jest-calculator/pull/15/commits/186245e75d65c26238abeccb86fed9c20e91980c) 커밋의 순서를 보더라도 작업 도중 잘못 된 점을 눈치채고 코드부터 수정하신 걸 확인할 수 있는데요,
여기서 아마 보통 작업하시던 방식대로 잘못 된 점을 수정하고 그에 맞춰서 테스트 케이스를 추가하신 것 같아요.

TDD를 기반으로 작업을 하려면 인지하신 순간에 테스트 케이스를 추가하고 작업을 진행하셔야 했겠지만, 
익숙하지 않으면 이렇게 바로 테스트를 작성하기는 많이 어려우실거에요. 지금처럼 작업 된 분량에 바로 테스트 케이스를 추가하는것도 좋습니다. 테스트를 잘 작성하는것에 익숙해지시는게 중요합니다.


> Q. 테스트 코드를 작성할 때, 어느 정도까지 테스트를 해야할지에 대한 고민이 드는 것 같습니다..! 혹시 리뷰어님의 기준이 있으시다면 여쭤보고 싶습니다!

아무리 잘 만들더라도 항상 에러와 대응하지 못한 여러 엣지케이스들은 있기 마련이긴 합니다.
익숙해지기 전 까지는 스스로 생각나는 것 + 리뷰받은 것을 참고하여 다양한 케이스들을 작성해보시길 권장합니다.

잘못 작성된 테스트 케이스는 코드의 리팩터링, 추가 구현을 방해하기도 하지만 그럴때마다 재정의를 하면서 익숙해지시는게 중요합니다!

다양한 엣지 케이스를 의미하는 여러 기준값들을 상수로 선언해서 잘 관리만 해도 부담이 많이 줄어들긴 합니다.(이 부분은 잘 해주신 것 같아요!)

> Q. 비슷한 로직들이 많은데 추상화 하는 부분이 어려운 것 같습니다.. 어떤 관점으로 추상화할 수 있을지, 어떤 관점으로 추상화 하면 좋을지 여쭤보고 싶습니다!

추상화에 대한 고민은 다음 과제에서 조금 더 고민해보면 좋을 것 같습니다. 앞으로 진행 될 미션들이 많아서 계산기 미션에서는 테스트 케이스에 대한 감을 익히는 정도로 하고 넘기시면 어떨까요?
섣부른 추상화는 어플리케이션을 복잡하게 만드는 부작용이 있습니다..!

> Q. 에러코드를 어떻게 처리하는 것이 좋을지(Ex. 각 모듈에서 에러코드 발생시키고 서비스 최 상단에서 catch하기) 여쭤보고 싶습니다.!

지금 작성하신 방법처럼 필요한곳에선 에러를 발생하고 사용처에서 catch를 잘 해주기만 해도 큰 문제는 없습니다. 중요한건 어플리케이션 전체의 에러 처리가 같은 기조를 가지고 작업되었는가 인 것 같습니다.
이 부분도 다음 미션에서 잘 챙겨보시면 좋을 것 같습니다!

2023-07-21 09:46 UTC, sonsurim commented on __tests__/Calculator.test.js
> +    it('2개의 양수에 대해 덧셈이 가능해야 합니다.', () => {
명수님 감사합니다! 혹시 위 문구에서 어떤 식으로 수정하면 좋을지 여쭤볼 수 있을까요!? 감이 잡히지 않아 도움 요청드립니다..!

2023-07-21 09:55 UTC, sonsurim commented on src/app.js
> +  return new Proxy(this, calculatorHandler)
명수님, 이번 미션에서 class 사용없이 생성자 함수로 작업해보고 싶어서 생성자 함수로 작업 해보았습니다! (특별한 이유는 없었습니다..ㅎㅎ)

proxy는 아래의 생각으로 인해 사용을 하였습니다..!
- 하나의 앱을 구현하는 과정이라 생각하였고 외부에서 앱이 변경 가능하면 안될 것 같다는 생각을 하였습니다.
- 앱의 특수한 값에 직접적인 접근 혹은 메서드를 변경할 때 핸들링을 한 곳에서 하면 좋을 것 같다는 생각을 하였습니다.

2023-07-21 13:13 UTC, carlos-dev-yang commented on __tests__/Calculator.test.js
> +    it('2개의 양수에 대해 덧셈이 가능해야 합니다.', () => {
2개의 양수에 대해 덧셈이 가능해야 한다.
또는
덧셈은 2개의 양수만 입력이 가능하다
등으로 수정하면 좋습니다. 문구는 편하게 작성해주세요!

2023-07-21 13:16 UTC, carlos-dev-yang commented on src/app.js
> +  return new Proxy(this, calculatorHandler)
아하 넵 proxy는 특이한 케이스가 아니면 잘 사용하지 않아서 궁금했었습니다.

일반 계산 기능 위에 공학용 기능을 추가한다던지, 세율을 계산한다던지 등의
계산 + 특수한 목적 형태로 계산이 붙으면 proxy를 붙일만하겠다 생각이 드네요.

오랜만에 proxy를 봐서 재밌기도 했습니다.

2023-07-21 13:21 UTC, carlos-dev-yang commented
@sonsurim 수림님만 괜찮으시면 이번 PR은 통과하고 다음 미션에 조금 더 주력해보시면 어떨까 합니다!
작업이 진행되면 그대로 올려주셔도 좋고, 작업 전이시고 다음 미션에 집중하고 싶으시면 바로 머지해도 충분할 것 같아요.

2023-07-21 13:59 UTC, sonsurim commented
@carlos-dev-yang 님 앗 넵 알겠습니다!! 리뷰 너무 감사드립니다!!ㅎㅎ

2023-07-21 14:00 UTC, sonsurim commented
@carlos-dev-yang 님 혹시 머지 권한이 없는 것 같은데 따로 요청드려야하는 걸까요..?!

2023-07-21 14:14 UTC, carlos-dev-yang commented
> @carlos-dev-yang 님 혹시 머지 권한이 없는 것 같은데 따로 요청드려야하는 걸까요..?!

넵 제가 머지해드리면 됩니다! 저도 지금 권한 부여가 안돼서.. 조금 걸릴 듯 합니다.
머지 기다리지 마시고 다음 미션 바로 진행하셔도 좋을 것 같습니다!

2023-07-21 14:23 UTC, sonsurim commented
@carlos-dev-yang 님 감사합니다!! 😍

2023-07-22 00:51 UTC, merged

2023-07-22 00:51 UTC, carlos-dev-yang commented
@sonsurim 머지 되었습니다. 온보딩 미션 수행하시느라 고생 많으셨어요!